name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Builder
      run: docker buildx create --name actionbuilder --driver docker-container
      
    - name: Use Builder
      run: docker buildx use actionbuilder

    - name: Build the Docker image
      run: docker buildx build . --file "16.0/Dockerfile" --platform linux/arm/v8 --tag my-image-name:$(date +%s)
